- name: RPM Fusion (Free ve Non-Free) Repo setup andd enabled for fedora
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  become: true
  when: ansible_facts['distribution'] == "Fedora"

- name: Terra Repo added system
  ansible.builtin.yum_repository:
    name: terra
    description: Terra Repository for Fedora
    baseurl: "https://repos.fyralabs.com/terra{{ ansible_facts['distribution_major_version'] }}"
    gpgcheck: false

- name: terra-release package setup
  ansible.builtin.dnf:
    name: terra-release
    state: present
